[package]
name = "hearth-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hearth-app = { path = "../hearth-app" }
hearth-bot = { path = "../hearth-bot" }
hearth-core = { path = "../hearth-core" }
hearth-fuzz = { path = "../hearth-fuzz" }
serde_json.workspace = true
